# Generated by Django 5.2.4 on 2025-07-25 15:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizzamodel',
            name='name',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message='Only alpha characters are allowed.', regex='^[A-Z][a-zA-Z ]{,29}$')]),
        ),
    ]
