# Generated by Django 5.2.4 on 2025-08-06 17:45

import core.services.service
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0002_alter_pizzamodel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizzamodel',
            name='photo',
            field=models.ImageField(blank=True, upload_to=core.services.service.upload_pizza_photo),
        ),
    ]
