# Generated by Django 5.2.4 on 2025-07-25 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profilemodel',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='usermodel',
            options={'ordering': ['id']},
        ),
    ]
